package net.golem.network.types;

public enum PlayStatus {
	LOGIN_SUCCESS,
	FAILED_CLIENT,
	FAILED_SERVER,
	PLAYER_SPAWN,
	FAILED_INVALID_TENANT,
	FAILED_VANILLA_EDU,
	FAILED_EDU_VANILLA,
	FAILED_SERVER_FULL
}
